name: story_kit
description: A flutter plugin for adapting screen.
version: 1.0.0
homepage: https://github.com/Moo-Meshrif/story_kit
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  cached_network_image: ^3.4.1
  better_player_plus: ^1.0.8
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
