name: story_kit
description: A flutter plugin for adapting screen.
version: 1.0.0
homepage: https://github.com/Moo-Meshrif/story_kit
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  cached_network_image: ^3.4.1
  video_player: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
